pub mod backend;
pub mod daemon;
pub mod diagnostics;
pub mod editor;
pub mod error;
pub mod mcp;
pub mod oneshot;
mod presentation;
pub mod process;
pub mod resolve;
pub mod responses;
pub mod server;
